apiVersion: v1
kind: Namespace
metadata:
  name: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: kube-event-metrics
rules:
- apiGroups: [""]
  resources:
  - events
  verbs: ["list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: kube-event-metrics
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-event-metrics
subjects:
- kind: ServiceAccount
  name: kube-event-metrics
  namespace: kube-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-event-metrics
  namespace: kube-system
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kube-event-metrics
    k8s-app: kube-event-metrics
  name: kube-event-metrics
  namespace: kube-system
spec:
  type: NodePort
  ports:
  - name: http-metrics
    port: 8080
    targetPort: metrics
    protocol: TCP
  selector:
    app: kube-event-metrics
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kube-event-metrics
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kube-event-metrics
    spec:
      serviceAccountName: kube-event-metrics
      containers:
      - name: kube-event-metrics
        image: tommyvn/k8s-event-metrics:v1.7.4-1
        ports:
        - name: metrics
          containerPort: 8080
        resources:
          requests:
            memory: 100Mi
            cpu: 100m
          limits:
            memory: 100Mi
            cpu: 100m
      - name: kubectl-proxy
        image: tommyvn/kubectl-proxy:v1.7.4-1
        resources:
          requests:
            memory: 64Mi
            cpu: 50m
          limits:
            memory: 64Mi
            cpu: 50m
